### ISSUE TITLE
what kind of hardware is needed?

### ISSUE THREAD

**Issue by delchrys** [susisstrolch/EMS-ESP8266_12-PCB#1]
Hello what kind of hardware is needed for this??
I've already made the rx/tx circuit from mikrocontroller.net.
Is it possible to direct put rx/tx from that circuit on the ESP8266??

kind regards,

Bert

**Comment by susisstrolch** [comment]
@Bert, sorry - I didn't notice your issue...
If you already have a working converter from ESP to RX/TX, you could use any kind of ESP device - WEMOS or NodeMCU.
You probably have to put a divider network between the converters TX and the ESP RX input to reduce the input voltage to 3,3V max.
