### ISSUE TITLE
Lack of Rezostor value on PCB

### ISSUE THREAD

**Issue by blacksocket** [susisstrolch/EMS-ESP8266_12-PCB#3]
Hello,

What value of rezistor should be on the PCB below R2 ? I cant find it on the BOM.

![image](https://user-images.githubusercontent.com/13651344/49188733-222a1180-f36c-11e8-8301-ed3bc7b7255c.png)

**Comment by susisstrolch** [comment]
somehow it got lost...
It's R14, Metall 10,0k
